export default {
    bio: {
        surname: "",
        other_names: "", 
        date_of_birth: "", 
        gender: "", 
        state_of_origin: "", 
        religion: "", 
        blood_group: "", 
        genotype: "", 
        student_allergy: "", 
        state_specific_illness: "", 
        last_school_attended: "", 
        class_last_passed: "", 
        class_last_passed_date: "", 
        quran_recitation: "", 
        identification_of_arabic_alphabets: "", 
        class_to_which_admission_is_sought: "", 
    },
    account: {
        ref_id: "",
        password: "",
        security_question: "",
        security_answer: "",
    },
    academic: {},
    father: {}, 
    mother: {}, 
    sponsor: {}
}